export type Mode='test'|'live';
export const LAUNCH_PRICES:Record<number,number>={3:2499,5:3499,10:6499};
export class CommerceError extends Error{constructor(public code:string,public status=400){super(code);}}
const enc=new TextEncoder();
const KEY_ALPHABET='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
export function uuid(v:unknown):string{if(typeof v!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v))throw new CommerceError('invalid_id');return v.toLowerCase();}
export function email(v:unknown):string|null{if(v==null||v==='')return null;if(typeof v!=='string'||v.length>254||!/^\S+@\S+\.\S+$/.test(v))throw new CommerceError('invalid_email');return v.trim().toLowerCase();}
export function safeMessage(error:unknown){if(error instanceof CommerceError)return{error:error.code,status:error.status};return{error:'commerce_unavailable',status:503};}
export function stripeConfiguration(get:(name:string)=>string|undefined){const mode=get('STRIPE_MODE');const secret=get('STRIPE_SECRET_KEY')||'';if((mode!=='test'&&mode!=='live')||(!secret.startsWith(`sk_${mode}_`)&&!secret.startsWith(`rk_${mode}_`)))throw new CommerceError('commerce_not_configured',503);return{mode:mode as Mode,secret};}
export async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',enc.encode(value.trim().toUpperCase()));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');}
export async function credential(secret:string,orderId:string){if(!secret)throw new CommerceError('commerce_not_configured',503);const id=uuid(orderId);const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(`cc-usd-license-v1|${id}`)));let raw='';for(let i=0;i<16;i++)raw+=KEY_ALPHABET[sig[i]%KEY_ALPHABET.length];return `CC-${raw.slice(0,4)}-${raw.slice(4,8)}-${raw.slice(8,12)}-${raw.slice(12,16)}`;}
function secureEqual(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0;}
export async function verifyStripeSignature(raw:string,header:string,secret:string){if(!secret.startsWith('whsec_')||!header)return false;const parts=header.split(',').map(x=>x.trim());const ts=parts.find(x=>x.startsWith('t='))?.slice(2)||'';const signatures=parts.filter(x=>x.startsWith('v1=')).map(x=>x.slice(3));const seconds=Number(ts);if(!Number.isInteger(seconds)||Math.abs(Math.floor(Date.now()/1000)-seconds)>300||!signatures.length)return false;const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(`${ts}.${raw}`)));const expected=Array.from(sig).map(b=>b.toString(16).padStart(2,'0')).join('');return signatures.some(s=>secureEqual(s.toLowerCase(),expected));}
export function validatePaidSession(session:any,items:any[],order:any,mode:Mode){if(!session||session.id!==order.stripe_session_id)throw new CommerceError('session_mismatch',400);if(Boolean(session.livemode)!==(mode==='live'))throw new CommerceError('environment_mismatch',400);if(session.mode!=='payment'||session.payment_status!=='paid'||session.status!=='complete')throw new CommerceError('payment_not_complete',400);if(session.client_reference_id!==order.id||session.metadata?.order_id!==order.id||Number(session.metadata?.slots)!==Number(order.slots))throw new CommerceError('payment_order_mismatch',400);if(session.currency!=='usd')throw new CommerceError('currency_mismatch',400);if(!Array.isArray(items)||items.length!==1)throw new CommerceError('line_item_mismatch',400);const item=items[0];if(Number(item.quantity)!==1||item.price?.id!==order.stripe_price_id||item.currency!=='usd')throw new CommerceError('line_item_mismatch',400);const subtotal=Number(session.amount_subtotal);const tax=Number(session.total_details?.amount_tax??0);const total=Number(session.amount_total);if(!Number.isInteger(subtotal)||subtotal!==Number(order.expected_amount)||Number(item.amount_subtotal)!==subtotal)throw new CommerceError('amount_mismatch',400);if(!Number.isInteger(tax)||tax<0||!Number.isInteger(total)||total!==subtotal+tax||Number(item.amount_total)!==subtotal+Number(item.amount_tax??0))throw new CommerceError('amount_mismatch',400);const paymentIntent=String(session.payment_intent||'');if(!paymentIntent.startsWith('pi_'))throw new CommerceError('payment_intent_missing',400);return{paymentIntent,subtotal,tax,total};}